DIOS- 4647: add history to diagnose and historySize parameter
millicast/millicast-sdk pull request #332
Opened 2024-03-26 00:31 UTC by keon-jukes

References https://jira.dolby.net/jira/browse/DIOS-4647

Screenshot of diagnose with history prop:
![history](https://github.com/millicast/millicast-sdk/assets/145141921/ca273fdf-cedc-4419-be17-a5457750a79b)

2024-04-01 20:40 UTC, Santiago-Souto approved these changes
LGTM

2024-04-01 20:41 UTC, Santiago-Souto commented
Make sure to come across the reason for the failed test before merging.

2024-04-03 17:33 UTC, Santiago-Souto requested changes

2024-04-03 17:33 UTC, Santiago-Souto commented on packages/millicast-sdk/src/config.js
> +  MILLICAST_DIRECTOR_ENDPOINT: 'https://director-dev.millicast.com',
This change is causing the E2E tests to fail, as the credentials used are for prod environment. I suggest to undo this, as it is important to test that environment with the SDK.

2024-04-08 10:24 UTC, vishalkharge commented
@keon-jukes @dubeyShivank 

Suggestion for method signature instead of 'Logger.diagnose(1, undefined, 'info')'

Suggested: 
	Logger.diagnose(statsCount, {historySize , minLogLevel})'
	Logger.diagnose(statsCount = MAX_STATS_HISTORY_SIZE, { historySize = MAX_HISTORY_SIZE, minLogLevel = 'TRACE'})

2024-04-08 10:26 UTC, vishalkharge commented
@keon-jukes, @dubeyShivank 

1. How did we derive the MAX history size of 10 i.e const MAX_HISTORY_SIZE = 10 ?

2. When I opened the viewer app, I saw below logs in the browser console:
[PeerConnection] 2024-04-08T09:55:22.321Z - INFO - Getting RTC peer status
[View] 2024-04-08T09:55:22.322Z - INFO - Broadcast status:  not_established
[Director] 2024-04-08T09:55:22.322Z - INFO - Getting subscriber connection data for stream name: Stream-V and account id: 4RFCzE
[PeerConnection] 2024-04-08T09:55:22.969Z - INFO - Creating new RTCPeerConnection
[PeerConnection] 2024-04-08T09:55:22.971Z - INFO - Getting RTC Local SDP
[PeerConnection] 2024-04-08T09:55:22.973Z - INFO - Creating peer offer
[Signaling] 2024-04-08T09:55:22.974Z - INFO - Connecting to Signaling Server
[PeerConnection] 2024-04-08T09:55:22.975Z - INFO - Peer offer created
[SdpParser] 2024-04-08T09:55:22.975Z - INFO - Replacing SDP response for support stereo
[SdpParser] 2024-04-08T09:55:22.975Z - INFO - Replaced SDP response for support stereo
[SdpParser] 2024-04-08T09:55:22.976Z - INFO - Setting multiopus
[SdpParser] 2024-04-08T09:55:22.976Z - INFO - Multiopus offer created
[SdpParser] 2024-04-08T09:55:22.977Z - INFO - Replaced SDP response for setting absolute capture time
[Signaling] 2024-04-08T09:55:23.704Z - INFO - WebSocket opened
[Signaling] 2024-04-08T09:55:23.704Z - INFO - Connected to server:  wss://live-ams-dev.millicast.com/ws/v2/sub/99d025409bfb4db19cf1e824a1bb56b4?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3MTI1NzAxMjMsImV4cCI6MTcxMjU3MDE4MywiaWF0IjoxNzEyNTcwMTIzLCJpc3MiOiJodHRwczovL2RpcmVjdG9yLWRldi5taWxsaWNhc3QuY29tIiwiYXVkIjoiTWlsbGljYXN0RGlyZWN0b3JSZXNvdXJjZSIsIm1pbGxpY2FzdCI6eyJ0eXBlIjoiU3Vic2NyaWJlIiwic3RyZWFtQWNjb3VudElkIjoiNFJGQ3pFIiwic3RyZWFtTmFtZSI6IlN0cmVhbS1WIiwic2VydmVySWQiOiI5OWQwMjU0MDliZmI0ZGIxOWNmMWU4MjRhMWJiNTZiNCIsImN1c3RvbURhdGEiOnsiaXNEaXJlY3RvciI6dHJ1ZSwicmVxdWVzdElkIjoiZDMwOTliYTEtMjMyZi00ZDkxLTkzMjAtZTkzYjAxMDZiMGNiIn19fQ.-AUYGT-po7_mGZq7zDhs68mw6uIjksy0aPhqNCUcnDc
[Signaling] 2024-04-08T09:55:23.705Z - INFO - Starting subscription to streamName:  Stream-V
[Signaling] 2024-04-08T09:55:23.705Z - INFO - Connecting to Signaling Server
[Signaling] 2024-04-08T09:55:23.705Z - INFO - Connected to server:  wss://live-ams-dev.millicast.com/ws/v2/sub/99d025409bfb4db19cf1e824a1bb56b4?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYmYiOjE3MTI1NzAxMjMsImV4cCI6MTcxMjU3MDE4MywiaWF0IjoxNzEyNTcwMTIzLCJpc3MiOiJodHRwczovL2RpcmVjdG9yLWRldi5taWxsaWNhc3QuY29tIiwiYXVkIjoiTWlsbGljYXN0RGlyZWN0b3JSZXNvdXJjZSIsIm1pbGxpY2FzdCI6eyJ0eXBlIjoiU3Vic2NyaWJlIiwic3RyZWFtQWNjb3VudElkIjoiNFJGQ3pFIiwic3RyZWFtTmFtZSI6IlN0cmVhbS1WIiwic2VydmVySWQiOiI5OWQwMjU0MDliZmI0ZGIxOWNmMWU4MjRhMWJiNTZiNCIsImN1c3RvbURhdGEiOnsiaXNEaXJlY3RvciI6dHJ1ZSwicmVxdWVzdElkIjoiZDMwOTliYTEtMjMyZi00ZDkxLTkzMjAtZTkzYjAxMDZiMGNiIn19fQ.-AUYGT-po7_mGZq7zDhs68mw6uIjksy0aPhqNCUcnDc
[Signaling] 2024-04-08T09:55:23.707Z - INFO - Sending view command
[Signaling] 2024-04-08T09:55:23.862Z - INFO - Command sent, subscriberId:  99d025409bfb4db19cf1e824a1bb56b4
[PeerConnection] 2024-04-08T09:55:23.863Z - INFO - Setting RTC Remote SDP
[PeerConnection] 2024-04-08T09:55:23.866Z - INFO - New track from peer.
[PeerConnection] 2024-04-08T09:55:23.867Z - INFO - New track from peer.
[PeerConnection] 2024-04-08T09:55:23.868Z - INFO - RTC Remote SDP was set successfully.
[View] 2024-04-08T09:55:23.868Z - INFO - Connected to streamName:  Stream-V
[PeerConnectionStats] 2024-04-08T09:55:23.868Z - INFO - Initializing peer connection stats
[PeerConnection] 2024-04-08T09:55:23.877Z - INFO - Peer connection state change:  connecting
[PeerConnection] 2024-04-08T09:55:24.293Z - INFO - Peer connection state change:  connected


But in the Logger.diagnose() I can only see the below log events i.e last 10 logs, I think with the last 10 log messages are we able to debug the viewer playback issues ?
We should include all the message from where the session was initiated

{
    "version": "0.1.44",
    "timestamp": 1712570133472,
    "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
    "accountId": "4RFCzE",
    "streamName": "Stream-V",
    "subscriberId": "99d025409bfb4db19cf1e824a1bb56b4",
    "connection": "connected",
    "history": [
        "[PeerConnection] 2024-04-08T09:55:23.866Z - INFO - New track from peer.",
        "[PeerConnection] 2024-04-08T09:55:23.866Z - DEBUG - Track event value:  {\"isTrusted\":true}",
        "[PeerConnection] 2024-04-08T09:55:23.867Z - INFO - New track from peer.",
        "[PeerConnection] 2024-04-08T09:55:23.867Z - DEBUG - Track event value:  {\"isTrusted\":true}",
        "[PeerConnection] 2024-04-08T09:55:23.868Z - INFO - RTC Remote SDP was set successfully.",
        "[PeerConnection] 2024-04-08T09:55:23.868Z - DEBUG - RTC Remote SDP new value:  ......",
        "[View] 2024-04-08T09:55:23.868Z - INFO - Connected to streamName:  Stream-V",
        "[PeerConnectionStats] 2024-04-08T09:55:23.868Z - INFO - Initializing peer connection stats",
        "[PeerConnection] 2024-04-08T09:55:23.877Z - INFO - Peer connection state change:  connecting",
        "[PeerConnection] 2024-04-08T09:55:24.293Z - INFO - Peer connection state change:  connected"
    ],

Which history logs should be shown in the diagnosis?

2024-04-08 10:26 UTC, vishalkharge commented
@keon-jukes , @dubeyShivank 

When the history size is set to -1, 0, or null, 20, it always displays the history with size 10.

2024-04-08 11:49 UTC, dubeyShivank commented
> @keon-jukes , @dubeyShivank
> 
> When the history size is set to -1, 0, or null, 20, it always displays the history with size 10.

Needs some degree of validation - 

it has to be a +ve integer - otherwise throw an exception ("Invalid Argument exception : historySize must be a positive integer")

2024-04-08 19:33 UTC, keon-jukes commented
![errorHandling](https://github.com/millicast/millicast-sdk/assets/145141921/ba6b7f4b-8405-41ac-a15a-7f156c8162c6)
Here is the update with error handling.

2024-04-09 19:00 UTC, Santiago-Souto requested changes
There should be a way to not depend on Logger for Diagnostics file or viceversa

2024-04-09 19:00 UTC, Santiago-Souto commented on packages/millicast-sdk/src/utils/Diagnostics.js
> +import Logger from '../Logger'
This is probably causing circular dependency warnings

2024-04-11 15:33 UTC, Santiago-Souto commented
@keon-jukes for the unit tests to pass you may need to update either adding a default value for `historySize` or passing in the tests a value for the exception to not be thrown. Also, you may need to add `history` as an attribute to check those tests.

2024-04-11 16:05 UTC, Santiago-Souto approved these changes
Ship it 🚀

2024-04-11 17:41 UTC, closed without merging