Remove deprecated property
millicast/millicast-sdk pull request #430
Opened 2024-08-28 02:04 UTC by dubeyShivank

`StreamName` is removed from everywhere

2024-08-28 15:17 UTC, Santiago-Souto requested changes

2024-08-28 15:17 UTC, Santiago-Souto commented on packages/millicast-sdk/src/utils/BaseWebRTC.js
> +import { log } from 'console'
This was a typo, wasn't it?
```suggestion
```

2024-08-28 23:19 UTC, dubeyShivank commented on packages/millicast-sdk/src/utils/BaseWebRTC.js
> +import { log } from 'console'
Hahh, yes :D

2024-08-30 14:14 UTC, Santiago-Souto approved these changes

2024-08-30 14:14 UTC, merged