Feature/get peer stats
millicast/millicast-sdk pull request #61
Opened 2021-05-25 20:50 UTC by R-Delfino95

2021-05-26 18:38 UTC, emilsas requested changes
In PeerConnectionStats, refactor all methods that don't use `this` to static.

2021-05-26 18:38 UTC, emilsas commented on packages/millicast-sdk/src/PeerConnectionStats.js
> +    }
```suggestion
  parseStats (rawStats) {
    this.previousStats = this.stats
    const statsObject = {
      audio: {
        inbound: {},
        outbound: {}
      },
      video: {
        inbound: {},
        outbound: {}
      },
      raw: rawStats
    }
```

2021-05-26 18:38 UTC, emilsas commented on packages/millicast-sdk/src/PeerConnectionStats.js
> +    return { raw: latestStats, ...statsObject }
```suggestion
    this.stats = statsObject
```

2021-05-26 18:38 UTC, emilsas commented on packages/millicast-sdk/src/PeerConnectionStats.js
> +      this.firstIntervalExecuted = true
```suggestion
      this.parseStats(stats)
```

2021-05-26 18:38 UTC, emilsas commented on packages/millicast-sdk/src/PeerConnectionStats.js
> +      if (this.firstIntervalExecuted) {
Remove this flag `this.firstIntervalExecuted`

2021-05-26 18:38 UTC, emilsas commented on packages/millicast-sdk/src/PeerConnectionStats.js
> +          additionalData.bitrate = 8 * (report.bytesReceived - previousBytes)
Set bitrate 0 if we didn't have previous Stats

2021-05-26 18:38 UTC, emilsas commented on packages/millicast-sdk/src/PeerConnectionStats.js
> +          additionalData.bitrate = 8 * (report.bytesSent - previousBytes)
Set bitrate 0 if we didn't have previous Stats

2021-05-26 18:38 UTC, emilsas commented on packages/millicast-sdk/src/PeerConnectionStats.js
> +   * @returns Object containing common information.
```suggestion
   * @returns {Object} Object containing common information.
```

2021-05-26 18:38 UTC, emilsas commented on packages/millicast-sdk/src/PeerConnectionStats.js
> +   * @param {Number|String} interval - Interval in seconds of how often it should get stats.
```suggestion
   * @param {Number} interval - Interval in seconds of how often it should get stats.
```

2021-05-26 18:38 UTC, emilsas commented on packages/millicast-sdk/src/PeerConnection.js
> +   * @param {Number|String} interval - Interval in seconds of how often it should get stats.
```suggestion
   * @param {Number} interval - Interval in seconds of how often it should get stats. Should be greater or equals to 1 second.
```

2021-05-26 18:38 UTC, emilsas commented on packages/millicast-sdk/src/PeerConnection.js
> +  getStats (interval = 1) {
```suggestion
  initStats (interval) {
```

2021-05-26 18:38 UTC, emilsas commented on packages/millicast-sdk/src/PeerConnectionStats.js
> +  getCodecData (codecReportId, latestStats) {
Capture mimetype in codecReport
`const { mimeType } =  codecReportId ? latestStats.get(codecReportId) : {}`

2021-05-26 21:23 UTC, R-Delfino95 commented
@emilsas your suggestions were applied.

2021-05-27 14:24 UTC, emilsas requested changes

2021-05-27 14:24 UTC, emilsas commented on packages/millicast-sdk/src/PeerConnection.js
> +      logger.warn('Cannot get peer stats: Already initialized')
```suggestion
      logger.warn('Cannot init peer stats: Already initialized')
```

2021-05-27 14:24 UTC, emilsas commented on packages/millicast-sdk/src/PeerConnection.js
> +      logger.warn('Cannot get peer stats: RTCPeerConnection not initialized')
```suggestion
      logger.warn('Cannot init peer stats: RTCPeerConnection not initialized')
```

2021-05-27 17:29 UTC, emilsas approved these changes

2021-05-27 17:35 UTC, merged